export const gift={
  emotes: [],
  comment: 'كبسو و برطاجو',
  userId: '7454060009569748014',
  secUid: 'MS4wLjABAAAAxG1hcgPC6RBUJOZ1OWvEH7YmmsT5nv2EOM_O0Wyt026BaVisUiwzNtlk6Z216emP',
  uniqueId: 'mokhtar.megaiz',
  nickname: '🇩🇿🇺🇸mokhtar megaiz',
  profilePictureUrl: 'https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/994f3478bcd4fab605cd7ca49b5cd2a4~tplv-tiktokx-cropcenter:100:100.webp?dr=9640&nonce=80195&refresh_token=8a64f0eb37b091b9cb575dc3d7588007&x-expires=1740690000&x-signature=ZLqhnVOFhKOsvBsu2VNaAtxmTRo%3D&idc=useast5&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474',
  followRole: 2,
  userBadges: [
    {
      type: 'privilege',
      privilegeId: '7138381176787572516',
      level: 9,
      badgeSceneType: 8
    },
    {
      type: 'privilege',
      privilegeId: '7196929090442513157',
      level: 7,
      badgeSceneType: 10
    }
  ],
  userSceneTypes: [ 8, 10 ],
  userDetails: {
    createTime: '0',
    bioDescription: '',
    profilePictureUrls: [
      'https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/994f3478bcd4fab605cd7ca49b5cd2a4~tplv-tiktokx-cropcenter:100:100.webp?dr=9640&nonce=80195&refresh_token=8a64f0eb37b091b9cb575dc3d7588007&x-expires=1740690000&x-signature=ZLqhnVOFhKOsvBsu2VNaAtxmTRo%3D&idc=useast5&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474',
      'https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/994f3478bcd4fab605cd7ca49b5cd2a4~tplv-tiktokx-cropcenter:100:100.webp?dr=9640&nonce=69372&refresh_token=dcb173a884c0e65c86e3a6866dfb8ef0&x-expires=1740690000&x-signature=ouqk%2Fu3IVlb7HewPiBuoR%2Br8EJs%3D&idc=useast5&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474',
      'https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/994f3478bcd4fab605cd7ca49b5cd2a4~tplv-tiktokx-cropcenter:100:100.jpeg?dr=9640&nonce=65679&refresh_token=a784421977b2ffa7c04f5253119fb7d5&x-expires=1740690000&x-signature=hex%2BJS3gRP8A9C7fhahVXNZLXv4%3D&idc=useast5&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474'
    ]
  },
  followInfo: {
    followingCount: 165,
    followerCount: 1427,
    followStatus: 2,
    pushStatus: 0
  },
  isModerator: false,
  isNewGifter: false,
  isSubscriber: false,
  topGifterRank: null,
  gifterLevel: 9,
  teamMemberLevel: 7,
  msgId: '7475468336608840490',
  createTime: '1740518113169'
}
// {
//   totalLikeCount: 18948,
//   likeCount: 7,
//   userId: '7312435148439487493',
//   secUid: 'MS4wLjABAAAACTpnoWs1Ju2q0DZNv_kyXRcX9e8jVfCwC7xK5t0G-BckjqLMpfRr-fKNEr53vHvd',
//   uniqueId: 'allilozouaoui',
//   nickname: 'Allilo Zouaoui',
//   profilePictureUrl: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/7312435533969162245~tplv-tiktokx-cropcenter:100:100.webp?dr=14579&nonce=77233&refresh_token=5dc3f7e9bcf2c209041cc0ff9ae7dd10&x-expires=1740690000&x-signature=%2Bvn2MJtI8c5uML8zzUGSCEy0nT8%3D&idc=maliva&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474',
//   followRole: 1,
//   userBadges: [],
//   userSceneTypes: [],
//   userDetails: {
//     createTime: '0',
//     bioDescription: '',
//     profilePictureUrls: [
//       'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/7312435533969162245~tplv-tiktokx-cropcenter:100:100.webp?dr=14579&nonce=77233&refresh_token=5dc3f7e9bcf2c209041cc0ff9ae7dd10&x-expires=1740690000&x-signature=%2Bvn2MJtI8c5uML8zzUGSCEy0nT8%3D&idc=maliva&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474',
//       'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/7312435533969162245~tplv-tiktokx-cropcenter:100:100.jpeg?dr=14579&nonce=317&refresh_token=bc68a214de4fecd4fbe625e3bd44d22f&x-expires=1740690000&x-signature=vvXZ8hmf%2FJFkT65OKSVIlUu7Mv0%3D&idc=maliva&ps=13740610&shcp=fdd36af4&shp=a5d48078&t=4d5b0474'
//     ]
//   },
//   followInfo: {
//     followingCount: 773,
//     followerCount: 222,
//     followStatus: 1,
//     pushStatus: 0
//   },
//   isModerator: false,
//   isNewGifter: false,
//   isSubscriber: false,
//   topGifterRank: null,
//   gifterLevel: 0,
//   teamMemberLevel: 0,
//   msgId: '7475468486890947077',
//   createTime: '1740518139990',
//   displayType: 'pm_mt_msg_viewer',
//   label: '{0:user} liked the LIVE'
// }
// Hurray! Connected! {
//   isConnected: true,
//   upgradedToWebsocket: true,
//   roomId: '7475458655381916418',
//   roomInfo: {
//     AnchorABMap: {},
//     adjust_display_order: 0,
//     admin_ec_show_permission: {},
//     admin_user_ids: [],
//     age_restricted: { AgeInterval: 0, restricted: false, source: 0 },
//     aigc_self_disclosure_switch: false,
//     allow_preview_time: 0,
//     anchor_scheduled_time_text: '',
//     anchor_share_text: '',
//     anchor_tab_type: 7,
//     answering_question_content: '',
//     app_id: 1233,
//     audio_mute: 0,
//     auto_cover: 0,
//     biz_sticker_list: [],
//     book_end_time: 0,
//     book_time: 0,
//     business_live: 0,
//     challenge_info: '',
//     client_version: 380703,
//     comment_has_text_emoji_emote: 0,
//     comment_name_mode: 0,
//     commerce_info: {
//       commerce_permission: 0,
//       oec_live_enter_room_init_data: '',
//       product_num: 0,
//       use_async_load: false,
//       use_new_promotion: 0
//     },
//     common_label_list: '',
//     content_tag: '',
//     continuous_room_quota_config: {},
//     cover: {
//       avg_color: '',
//       height: 0,
//       image_type: 0,
//       is_animated: false,
//       open_web_url: '',
//       uri: '720x720/tos-maliva-avt-0068/3a4196ef5c77cc7477322af50e183ed6',
//       url_list: [Array],
//       width: 0
//     },
//     cover_type: 0,
//     cpp_version: 0,
//     create_time: 1740515863,
//     deco_list: [],
//     deprecated10: '',
//     deprecated11: '',
//     deprecated12: '',
//     deprecated13: '',
//     deprecated14: 0,
//     deprecated15: 0,
//     deprecated16: 0,
//     deprecated17: [],
//     deprecated18: 0,
//     deprecated19: '',
//     deprecated195: false,
//     deprecated2: '',
//     deprecated20: 0,
//     deprecated21: false,
//     deprecated22: 0,
//     deprecated23: '',
//     deprecated24: 0,
//     deprecated26: '',
//     deprecated28: '',
//     deprecated3: {},
//     deprecated30: '',
//     deprecated31: false,
//     deprecated32: '',
//     deprecated35: 0,
//     deprecated36: 0,
//     deprecated39: '',
//     deprecated4: 0,
//     deprecated41: 0,
//     deprecated43: false,
//     deprecated44: 0,
//     deprecated5: false,
//     deprecated6: '',
//     deprecated7: 0,
//     deprecated8: '',
//     deprecated9: '',
//     disable_preload_stream: false,
//     disable_preview_sub_only: 0,
//     disable_screen_record: false,
//     drawer_tab_position: '',
//     drop_comment_group: 0,
//     ec_age_interval: 0,
//     ecommerce_room_tags: [],
//     effect_frame_upload_demotion: 0,
//     effect_info: [],
//     emoji_list: [],
//     enable_optimize_sensitive_word: false,
//     enable_server_drop: 0,
//     enable_stream_encryption: false,
//     existed_commerce_goods: false,
//     fansclub_msg_style: 2,
//     feed_room_label: {
//       avg_color: '#EBFBFF',
//       height: 0,
//       image_type: 0,
//       is_animated: false,
//       open_web_url: '',
//       uri: 'webcast-sg/2ea90002aca1159b5c67',
//       url_list: [Array],
//       width: 0
//     },
//     feed_room_labels: [],
//     filter_msg_rules: [],
//     finish_reason: 0,
//     finish_time: 1740515863,
//     finish_url: '',
//     finish_url_v2: '',
//     follow_msg_style: 2,
//     forum_extra_data: '',
//     game_demo: 0,
//     game_tag: [ [Object] ],
//     gift_msg_style: 2,
//     gift_poll_vote_enabled: false,
//     group_source: 0,
//     has_commerce_goods: false,
//     has_more_history_comment: false,
//     has_used_music: false,
//     have_wishlist: false,
//     history_comment_cursor: '',
//     history_comment_list: [],
//     hot_sentence_info: '',
//     id: 7475458655381917000,
//     id_str: '7475458655381916418',
//     idc_region: '',
//     indicators: [],
//     interaction_question_version: 0,
//     introduction: '',
//     is_gated_room: false,
//     is_replay: false,
//     is_show_user_card_switch: false,
//     last_ping_time: 0,
//     layout: 0,
//     like_count: 0,
//     link_mic: {
//       audience_id_list: [],
//       battle_scores: [Array],
//       battle_settings: [Object],
//       channel_id: 7475467124597722000,
//       channel_info: [Object],
//       followed_count: 0,
//       linked_user_list: [],
//       multi_live_enum: 1,
//       rival_anchor_id: 7467628950190376000,
//       show_user_list: []
//     },
//     linker_map: { '2': 7475467124597722000 },
//     linkmic_layout: 0,
//     lite_user_not_visible: false,
//     lite_user_visible: false,
//     live_distribution: [],
//     live_id: 12,
//     live_reason: '',
//     live_room_mode: 0,
//     live_sub_only: 0,
//     live_sub_only_month: 0,
//     live_sub_only_tier: 0,
//     live_sub_only_use_music: 0,
//     live_type_audio: false,
//     live_type_linkmic: false,
//     live_type_normal: true,
//     live_type_sandbox: false,
//     live_type_screenshot: false,
//     live_type_social_live: false,
//     live_type_third_party: false,
//     living_room_attrs: {
//       admin_flag: 0,
//       rank: 0,
//       room_id: 7475458655381917000,
//       room_id_str: '7475458655381916418',
//       silence_flag: 0
//     },
//     lottery_finish_time: 0,
//     max_continue_watch_mill_seconds: 0,
//     max_preview_time: 0,
//     mosaic_status: 0,
//     multi_stream_id: 0,
//     multi_stream_id_str: '',
//     multi_stream_scene: 0,
//     multi_stream_source: 0,
//     net_mode: 0,
//     os_type: 0,
//     owner: {
//       allow_find_by_contacts: false,
//       allow_others_download_video: false,
//       allow_others_download_when_sharing_video: false,
//       allow_share_show_profile: false,
//       allow_show_in_gossip: false,
//       allow_show_my_action: false,
//       allow_strange_comment: false,
//       allow_unfollower_comment: false,
//       allow_use_linkmic: false,
//       avatar_large: [Object],
//       avatar_medium: [Object],
//       avatar_thumb: [Object],
//       badge_image_list: [],
//       badge_list: [],
//       bg_img_url: '',
//       bio_description: 'تحيا 🇩🇿',
//       block_status: 0,
//       border_list: [],
//       comment_restrict: 0,
//       commerce_webcast_config_ids: [],
//       constellation: '',
//       create_time: 0,
//       deprecated1: 0,
//       deprecated12: 0,
//       deprecated13: 0,
//       deprecated15: 0,
//       deprecated16: false,
//       deprecated17: false,
//       deprecated18: '',
//       deprecated19: false,
//       deprecated2: 0,
//       deprecated21: 0,
//       deprecated28: false,
//       deprecated29: '',
//       deprecated3: 0,
//       deprecated4: 0,
//       deprecated5: '',
//       deprecated6: 0,
//       deprecated7: '',
//       deprecated8: 0,
//       disable_ichat: 0,
//       display_id: 'gatouti_31',
//       enable_ichat_img: 0,
//       exp: 0,
//       fan_ticket_count: 0,
//       fold_stranger_chat: false,
//       follow_info: [Object],
//       follow_status: 0,
//       ichat_restrict_type: 0,
//       id: 7330211572412122000,
//       id_str: '7330211572412122144',
//       is_anchor_marked: false,
//       is_block: false,
//       is_follower: false,
//       is_following: false,
//       is_subscribe: false,
//       link_mic_stats: 0,
//       media_badge_image_list: [],
//       mint_type_label: [Array],
//       modify_time: 1740515864,
//       need_profile_guide: false,
//       new_real_time_icons: [],
//       nickname: 'ولد السهلي',
//       own_room: [Object],
//       pay_grade: [Object],
//       pay_score: 0,
//       pay_scores: 0,
//       push_comment_status: false,
//       push_digg: false,
//       push_follow: false,
//       push_friend_action: false,
//       push_ichat: false,
//       push_status: false,
//       push_video_post: false,
//       push_video_recommend: false,
//       real_time_icons: [],
//       scm_label: '',
//       sec_uid: 'MS4wLjABAAAAZAnNzV5NF5EgRHkjFBHa2ivkexlEPBP2wn7Y63w-dxEoQervjMIrKPxaNMJCWJ2F',
//       secret: 0,
//       share_qrcode_uri: '',
//       special_id: '',
//       status: 1,
//       ticket_count: 0,
//       top_fans: [],
//       top_vip_no: 0,
//       upcoming_event_list: [],
//       user_attr: [Object],
//       user_role: 0,
//       verified: false,
//       verified_content: '',
//       verified_reason: '',
//       with_car_management_permission: false,
//       with_commerce_permission: false,
//       with_fusion_shop_entry: false
//     },
//     owner_device_id: 0,
//     owner_device_id_str: '',
//     owner_user_id: 7330211572412122000,
//     owner_user_id_str: '7330211572412122144',
//     paid_event: { event_id: 0, paid_type: 0 },
//     partnership_info: {
//       partnership_room: false,
//       promoting_drops_id: '',
//       promoting_game_id: '',
//       promoting_room: false,
//       promoting_task_id: '',
//       promoting_task_type: 0,
//       show_task_id: '',
//       show_task_type: 0,
//       task_id_list: []
//     },
//     pico_live_type: 0,
//     polling_star_comment: false,
//     pre_enter_time: 0,
//     preview_flow_tag: 0,
//     quota_config: {},
//     rank_comment_groups: [],
//     ranklist_audience_type: 0,
//     regional_restricted: { block_list: [] },
//     relation_tag: '',
//     replay: true,
//     reposted: false,
//     room_audit_status: 0,
//     room_auth: {
//       Banner: 1,
//       BroadcastMessage: 0,
//       Chat: true,
//       ChatL2: false,
//       ChatSubOnly: false,
//       CommercePermission: 0,
//       CommunityFlagged: false,
//       CommunityFlaggedReview: false,
//       CustomizableGiftPoll: 0,
//       CustomizablePoll: 0,
//       Danmaku: false,
//       Digg: true,
//       DonationSticker: 2,
//       EmotePoll: 0,
//       EnableFansLevel: false,
//       EnableShowUserUV: false,
//       EventPromotion: 0,
//       Explore: false,
//       GameRankingSwitch: 0,
//       Gift: true,
//       GiftAnchorMt: 1,
//       GiftPoll: 0,
//       GoldenEnvelope: 0,
//       GoldenEnvelopeActivity: 0,
//       InteractionQuestion: true,
//       Landscape: 2,
//       LandscapeChat: 0,
//       LuckMoney: true,
//       MultiEnableReserve: false,
//       Pictionary: 0,
//       PictionaryBubble: 0,
//       PictionaryPermission: 0,
//       Poll: 0,
//       Promote: false,
//       PromoteOther: 0,
//       Props: false,
//       PublicScreen: 1,
//       QuickChat: 0,
//       Rank: 0,
//       RankingChangeAlterSwitch: 0,
//       RoomContributor: false,
//       SecretRoom: 0,
//       Share: true,
//       ShareEffect: 0,
//       ShoppingRanking: 0,
//       SpamComments: false,
//       UserCard: true,
//       UserCount: 1,
//       Viewers: false,
//       comment_tray_status: 0,
//       credit_entrance_for_audience: false,
//       deprecated1: false,
//       deprecated118: [],
//       deprecated119: 0,
//       deprecated2: 0,
//       deprecated3: 0,
//       deprecated4: 0,
//       deprecated5: 0,
//       deprecated6: 0,
//       deprecated7: 0,
//       deprecated8: 0,
//       deprecated9: 0,
//       game_guess_permission: false,
//       guess_entrance_for_host: false,
//       show_credit_widget: false,
//       transaction_history: 1,
//       use_user_pv: false
//     },
//     room_create_ab_param: '',
//     room_layout: 0,
//     room_llm_title: '',
//     room_pcu: 0,
//     room_sticker_list: [],
//     room_tabs: [],
//     room_tag: 0,
//     rtc_app_id: '',
//     scroll_config: '',
//     search_id: 0,
//     share_msg_style: 2,
//     share_url: 'https://m.tiktok.com/share/live/7475458655381916418/?language=en',
//     short_title: '',
//     short_touch_items: [],
//     show_star_comment_entrance: false,
//     social_interaction: { linkmic_scene_linker: {}, multi_live: [Object] },
//     start_time: 0,
//     stats: {
//       deprecated1: 0,
//       deprecated2: '',
//       digg_count: 0,
//       enter_count: 0,
//       fan_ticket: 0,
//       follow_count: 10,
//       gift_uv_count: 0,
//       id: 7475458655381917000,
//       id_str: '7475458655381916418',
//       like_count: 0,
//       replay_fan_ticket: 0,
//       replay_viewers: 1421,
//       share_count: 0,
//       total_user: 1739,
//       total_user_desp: '',
//       watermelon: 0
//     },
//     status: 2,
//     sticker_list: [],
//     stream_id: 7475458692707847000,
//     stream_id_str: '7475458692707846934',
//     stream_status: 0,
//     stream_url: {
//       alive_timestamp: 0,
//       candidate_resolution: [Array],
//       complete_push_urls: [],
//       default_resolution: 'ORIGION',
//       drm_type: 0,
//       extra: [Object],
//       flv_pull_url: [Object],
//       flv_pull_url_params: [Object],
//       hls_pull_url: '',
//       hls_pull_url_map: {},
//       hls_pull_url_params: '{"VCodec":"h264","stream_suffix":"or4","vbitrate":1000000,"resolution":"1080x1920","gop":4}',      
//       id: 7475458692707847000,
//       id_str: '7475458692707846934',
//       live_core_sdk_data: [Object],
//       provider: 0,
//       push_resolution: '',
//       push_urls: [],
//       resolution_name: [Object],
//       rtmp_pull_url: 'https://pull-f5-tt04.tiktokcdn.com/stage/stream-7475458692707846934_or4.flv?expire=1741727740&session_id=048-2025022521153944C73A5F477F748943B3&sign=23d86bcc6fff5b797aba6b87580eddb6',
//       rtmp_pull_url_params: '{"VCodec":"h264","stream_suffix":"or4","vbitrate":1000000,"resolution":"1080x1920","gop":4}',     
//       rtmp_push_url: '',
//       rtmp_push_url_params: '',
//       stream_app_id: 0,
//       stream_control_type: 0,
//       stream_delay_ms: 0,
//       stream_size_height: 0,
//       stream_size_width: 0,
//       vr_type: 0
//     },
//     stream_url_filtered_info: { is_gated_room: false, is_paid_event: false },
//     sub_tag: 0,
//     support_quiz: 0,
//     title: '🇩🇿🫶🏼🇩🇿' ,
//     top_fans: [ [Object], [Object], [Object] ],
//     use_filter: false,
//     user_count: 93,
//     user_share_text: '',
//     video_feed_tag: '',
//     watch_early_quota_config: {},
//     webcast_comment_tcs: 0,
//     webcast_sdk_version: 0,
//     with_draw_something: false,
//     with_ktv: false,
//     with_linkmic: false
//   },
//   availableGifts: undefined
// }
